### ISSUE TITLE
Page completly blank on 0.110.0.dev20200510

### ISSUE THREAD

**Issue by chemelli74** [custom-components/uilogs#11]
Updated test environment to one of the latest dev build and page is completely blank:

![image](https://user-images.githubusercontent.com/57354320/81566804-b0952600-939b-11ea-92f8-d692c2bd1b91.png)

Simone

**Comment by ludeeus** [comment]
Fixed https://github.com/custom-components/uilogs/commit/2c7d7e74267950dedc28bf998f4d8b03aca15522
