### ISSUE TITLE
Reverse order

### ISSUE THREAD

**Issue by benleb** [custom-components/uilogs#13]
Hey ludeeus, what do you think about reversing the log order, putting the newest to the top? That would avoid scrolling thousands (or tens of thousands...) of lines to get to the probably most interesting logs

**Comment by ludeeus** [comment]
I think that would be confusing since every other log in HA is the other way.
If will also add more overhead to the runtime, which again will make it slower.
I will not be implementing that.

But feel free to do so in a PR, but make it configurable, with a default to the current way.

**Comment by quack3d** [comment]
I second this suggestion.
