### ISSUE TITLE
0.112.x - Plugin doesn't work anymore

### ISSUE THREAD

**Issue by chemelli74** [custom-components/uilogs#15]
Updated my test env to latest and this great plugin doesn't work anymore:

![image](https://user-images.githubusercontent.com/57354320/85987943-a2a07080-b9ee-11ea-8ef8-479050176b41.png)

Simone

**Comment by stickpin** [comment]
Now when 0.112 is officially released, i see that the issue is present:
`2020-07-01 20:46:51 ERROR (MainThread) [frontend.js.latest.202007010] http://192.168.1.20:8123/api/panel_custom/uilogs:20:11471 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry`

**Comment by wjbridge** [comment]
Seeing this also:

`uilogs:20:11471 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry`

**Comment by fufar** [comment]
same error, 0.112.2

```
Уровень: ERROR
Logger: frontend.js.latest.202007020
Source: components/system_log/__init__.py:209
First occurred: 13:32:20 (2 occurrences)
Last logged: 14:10:54

https://example.com/api/panel_custom/uilogs:20:11471 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry
```

**Comment by chemelli74** [comment]
That's the automation situation:

![image](https://user-images.githubusercontent.com/57354320/86479197-fb07a300-bd4b-11ea-82ed-a2cd0ca16821.png)

But still CPU is more that 40%.

New profile: [profile3.zip](https://github.com/custom-components/uilogs/files/4870237/profile3.zip)

Simone

**Comment by caiosweet** [comment]
@wjbridge I had the same problem.  A reboot of the host was enough and it started working again.

**EDIT.** Sorry. No luck. reboot does not help... as AdmiralStipe said

**Comment by AdmiralStipe** [comment]
Same problem here, reboot does not help...

**Comment by ludeeus** [comment]
There is a conflict in imports.
To solve this it needs a complete rewrite to use iframe.

**Comment by v1-valux** [comment]
You can refresh the tab to make them temporarily work again. (workaround)

**Comment by RobHofmann** [comment]
Same error here

```
app.9108bd0a.js:43757 Error loading page lovelace DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry
    at https://home.hofmann.nl/frontend_latest/app.9108bd0a.js:709:57050
    at https://home.hofmann.nl/frontend_latest/app.9108bd0a.js:709:57065
    at s (https://home.hofmann.nl/frontend_latest/app.9108bd0a.js:2:20580)
    at Object.281 (https://home.hofmann.nl/frontend_latest/chunk.5cd6ebaa3e3e7e5d9059.js:973:10084)
    at i (https://home.hofmann.nl/frontend_latest/app.9108bd0a.js:2:367)
    at Module.842 (https://home.hofmann.nl/frontend_latest/chunk.5cd6ebaa3e3e7e5d9059.js:3171:4094)
    at i (https://home.hofmann.nl/frontend_latest/app.9108bd0a.js:2:367)
```

Refresh does work as a workaround :)

**Comment by aespejou** [comment]
This has been broken for a while now. Will it be fixed eventually or is this deprecated?

**Comment by ludeeus** [comment]
@aespejou 
> There is a conflict in imports.
To solve this it needs a complete rewrite to use iframe.

> You can refresh the tab to make them temporarily work again. (workaround)

**Comment by chemelli74** [comment]
Should we consider the plugin as archived ? Or there is some work under the wood to make it working with newer HA versions ?

Thx in advance,

Simone

**Comment by ludeeus** [comment]
Currently, I have spent 15-20 hours on getting it working.
It needs a **complete** rewrite to use iframe so it does not crash with the elements used in HA.

The workaround offered still works.

**Comment by andker87** [comment]
HA Core 0.115.2
`ERROR (MainThread) [frontend.js.latest.202009180] https://xxxxxxxxxx.duckdns.org:YYYY/api/panel_custom/uilogs:20:11471 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mwc-list-item" has already been used with this registry`

Refresh workaround works, but I really hope it will be fixed, this custom_component is really nice

**Comment by xekil** [comment]
Hello,
An update is planned?
Maybe someone should make a fork

**Comment by Quotacious** [comment]
**Stop - Before you post:**  A lot of work is required to fix and ludeeus has already put 20 hours into the fix so far. He has requested help, so the offer is already there to assist if you have the skills to do so.

@ludeeus Would you consider renaming the menu entry to **Logs (Ctrl-r)**?  This may help with the continued confusion in the meantime.  As you said, it works **perfect** once you reload once. I think we all just need a heads up or a reminder on the very simple work-around. Thanks for creating it and sharing it with us.

**Comment by chemelli74** [comment]
Latest dev build of HA introduced colors for error and warning.

Taking care there there is too much effort on porting this plugin to latest HA builds, I'm going to close this issue even if it's not solved.

Simone
