### ISSUE TITLE
[Bug] Blank "Supervisor" and "Addons" page and only WARNINGs in "Core"

### ISSUE THREAD

**Issue by CodeFinder2** [custom-components/uilogs#4]
Hi,

after updating to the latest version (8d1ee4d) with newest HA (v0.107), my "Core" tab only contains the recent warnings, but not INFO and/or DEBUG logs. 🤔 

Also, the "Supervisor" is completely white (I have the "Amoled" theme active) and the same applies for the "Addons" tab, regardless of the selected addon.

Do you have an idea what's going wrong?

I've already, reloaded the page in my browser, restarted HA a few times and reinstalled _UI Logs_ once without success.

Thanks!

EDIT: forgot to mention that this seemed to occur _after_ this last update.

EDIT2: tested in Chrome, Firefox and official HA android app.

**Comment by CodeFinder2** [comment]
Hm, okay the bug seemed to have disappeared over night?!

Although I just realized that, for instance, the log of "zigbee2mqtt" is not up-to-date (regardless of clicking/spamming the "refresh button" in the upper right). There are newer entries in the addon logs compared to what's being displayed in UI Logs for that addon. This is another bug.

Reloading the page or temporarily selecting another addon seems to fix it but the refresh button does not seem to do its job ... :see_no_evil: 

(This is different from my initially opened issue so I can open another issue if you want me to. ;-) )

Edit: bug (blank page for addons on mobile this time) happened again...

**Comment by jonwaland** [comment]
installed - 8d1ee4d
Home Assistant 0.106.6


only WARNING Shows in LogUI - but I have loads of ERROR in the Developer Tools log...

(added here as it seems same bug...?)

**Comment by ludeeus** [comment]
fixed now, forgot to publish the build when I fixed the issue...

**Comment by CodeFinder2** [comment]
Thanks!
