### ISSUE TITLE
[Feature requests] Auto-reload upon changes, entry filter, and more

### ISSUE THREAD

**Issue by CodeFinder2** [custom-components/uilogs#6]
Hi,

I really like this integration and use it a lot since it combines all the logs very conveniently! It also works MUCH better than the official "Log Viewer" (which sometime does not connect, update, etc.) - don't use it anymore once I found yours. 😎 

Nonetheless, I have a few suggestions for improvements if you don't mind:
- show the most recent logs at the beginning/top so it's unnecessary to always scroll to the end
- automatically reload the log(s) if new entries occur (or is polling the only option? then HA may require updates in its backend ...); this would be the most valuable extension (maybe add an additional checkbox to dynamically enable/disable this). It may also require an "auto-scroll" feature upon updates (which may also deserves a checkbox) but this seems to be implemented already anyway. ;-) I know about the "refresh" button but "spamming" this button frequently when you expect to see an output is very annoying. If it's only possible to poll then maybe add a periodic (configurable) timer to do the polling frequently (although I would consider this as a workaround since there should be a way via HA).
- highlighting for addon logs does not work for all of them/mine (e.g., zigbee2mqtt). Maybe we can provide some sort of regex to add that to more addons (at least for debug, info, warning and error) and/or configure a default color for all non-matching entries?
- add a search box / filter to only display entries with specific terms (and possibly allow wildcards)

Maybe it's better to make these or some of these things optional (requiring a settings menu) to let the user select what to prefer. Honestly, I also don't know how difficult it is to realize this... 🙈 

These would make this integration even more useful to me, thanks for considering! :-)

**Comment by ludeeus** [comment]
> show the most recent logs at the beginning/top so it's unnecessary to always scroll to the end.

This is controlled by HA/supervisor, and will not be reasonable to mangle in this integration.

> automatically reload the log(s) if new entries occur

This is not possible, the logs need to be fetched, there are no events that say when an entry is added to the log, that would be pretty harmful to the performance.

> highlighting for addon logs does not work for all of them/mine

This integration uses this library to determine the color used <https://github.com/ludeeus/colorlog> feel free to add more options there 👍  

> add a search box / filter

This is planed, and are already partially in the code already ;)

**Comment by ludeeus** [comment]
filter implemented here https://github.com/custom-components/uilogs/commit/2c7d7e74267950dedc28bf998f4d8b03aca15522

**Comment by CodeFinder2** [comment]
@ludeeus Thanks for the update! "automatically reload the log(s) if new entries occur" is at least implemented in the official ["Log viewer" addon](https://github.com/hassio-addons/addon-log-viewer) so I thought its possible here as well?

**Comment by ludeeus** [comment]
That one does constant polling, which is fine as it runs in a separate container, if we where to do the same in your main container, it will break

**Comment by CodeFinder2** [comment]
Alright, thanks for clarification!
