### ISSUE TITLE
Installation via HACS ask to overwrite "custom_components"

### ISSUE THREAD

**Issue by chemelli74** [custom-components/uilogs#8]
If you already have installed a component via HACS ,when you try to install this one you get a message that if you continue "custom_components" will be overwritten.

Message is misleading and should be removed.

Simone

**Comment by ludeeus** [comment]
And that only happens with this integration?

**Comment by chemelli74** [comment]
> And that only happens with this integration?

Yes, exactly.

Simone

**Comment by ludeeus** [comment]
I can not replecate this issue.
a) It's fixed in this integration
b) It's fixed in HACS
